name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  unit-test:
    container: cuaesd/aesd-autotest:24-unit-test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Check permissions before setting
        run: ls -l ./unit-test.sh
      - name: Set execute permissions
        run: chmod +x ./unit-test.sh
      - name: Check permissions after setting
        run: ls -l ./unit-test.sh
      - name: Run unit test
        run: ./unit-test.sh

  full-test:
    container: cuaesd/aesd-autotest:24-assignment2
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Check permissions before setting
        run: ls -l ./full-test.sh
      - name: Set execute permissions
        run: chmod +x ./full-test.sh
      - name: Check permissions after setting
        run: ls -l ./full-test.sh
      - name: Run full test
        run: ./full-test.sh
