name: assignment-test

on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'

jobs:
    unit-test:
        container: cuaesd/aesd-autotest:24-unit-test
        runs-on: self-hosted
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Checkout submodules
            run: git submodule update --init --recursive

          - name: Fix permissions for unit-test.sh
            run: chmod +x unit-test.sh

          - name: Verify unit-test.sh permissions
            run: ls -l unit-test.sh

          - name: Run unit test
            run: bash unit-test.sh

    full-test:
        container: cuaesd/aesd-autotest:24-assignment2
        runs-on: self-hosted
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Checkout submodules
            run: git submodule update --init --recursive

          - name: Fix permissions for full-test.sh
            run: chmod +x full-test.sh

          - name: Verify full-test.sh permissions
            run: ls -l full-test.sh

          - name: Run full test
            run: bash full-test.sh

